increasing the time out as I'm seeing errors like this, which is legitimate:
java.lang.AssertionError: Hudson is still doing something after 30000ms: queue=[] building=[snap-dep-test-down #2]
	at org.jvnet.hudson.test.HudsonTestCase.waitUntilNoActivityUpTo(HudsonTestCase.java:801)
	at org.jvnet.hudson.test.HudsonTestCase.waitUntilNoActivity(HudsonTestCase.java:772)
	at hudson.maven.MavenSnapshotTriggerTest.testMixedTransitiveSnapshotTrigger(MavenSnapshotTriggerTest.java:69)
	at org.jvnet.hudson.test.HudsonTestCase.runTest(HudsonTestCase.java:310)
	at com.sun.maven.junit.LocalTestCaseRunner.runTests(LocalTestCaseRunner.java:100)
	at com.sun.maven.junit.LocalTestCaseRunner.runTestCase(LocalTestCaseRunner.java:51)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:274)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:255)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:215)
	at hudson.remoting.UserRequest.perform(UserRequest.java:104)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:250)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:619)

git-svn-id: https://hudson.dev.java.net/svn/hudson/trunk/hudson/main@24847 71c3de6d-444a-0410-be80-ed276b4c234a

Originally-Committed-As: 03b448805427a20ef080d09e6cefaa9b928e3d7e